# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_lifetime: 3600  # Sesión expira en 1 hora
        gc_maxlifetime: 3600   # Garbage collector elimina sesiones inactivas después de 1 hora
        cookie_secure: auto    # Usa HTTPS si disponible
        cookie_samesite: lax   # Para seguridad

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
